### ISSUE TITLE
Oracle 11g Support?

### ISSUE THREAD

**Issue by jabrwoky** [PhilippSalvisberg/plscope-utils#29]
Hi, 
Trying to build on Oracle 11g Enterprise Edition Release 11.2.0.4.0 

I had Plscope installed and recompiled all objects so there is existing data for plscope.

When  running @database/utils/user/plscope.sql I get:

`GRANT SELECT ON sys.dba_statements   TO PLSCOPE WITH GRANT OPTION
                    *
ERROR at line 1:
ORA-00942: table or view does not exist`

Though dba_identifiers does exist.

When running @database/install.sql I get:
Also, there appears to be a dependency on Oracle Real Application Security packages, which I do not have installed.
`     ace  => sys.xs$ace_type(
             *
ERROR at line 4:
ORA-06550: line 4, column 14:
PLS-00201: identifier 'SYS.XS$ACE_TYPE' must be declared
ORA-06550: line 2, column 3:
PL/SQL: Statement ignored`

There also appears to be a dependency on SYS.DBA_STATEMENTS, which also appears to be an Oracle 12 object at:

`Errors for PACKAGE BODY LINEAGE_UTIL:

LINE/COL ERROR
-------- -----------------------------------------------------------------
188/14	 PLS-00341: declaration of cursor 'C_INSERT' is incomplete or
	 malformed

189/10	 PL/SQL: SQL Statement ignored
190/17	 PL/SQL: ORA-00942: table or view does not exist`

There are other errors that I suspect are noise due to previous errors.

Is there a version of this utility that will work with 11g? 
Thanks!

**Comment by PhilippSalvisberg** [comment]
plscope-utils has two components:

- [Core Database Objects](https://github.com/PhilippSalvisberg/plscope-utils/blob/master/database/README.md)
  requires Oracle Database 12.2 or higher, see [prerequisites](https://github.com/PhilippSalvisberg/plscope-utils/blob/master/database/README.md#prerequisites)

- [SQL Developer Extension](https://github.com/PhilippSalvisberg/plscope-utils/blob/master/sqldev/README.md)
  requires Oracle Database 11.1 or higher, see [prerequisites](https://github.com/PhilippSalvisberg/plscope-utils/blob/master/sqldev/README.md#prerequisites).

There are no plans to support Oracle 11g for the [Core Database Objects](https://github.com/PhilippSalvisberg/plscope-utils/blob/master/database/README.md) since most of the code relies on the availability of the [`DBA_STATEMENTS`](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/ALL_STATEMENTS.html#GUID-36FF82A6-DD4B-45E4-8B46-2ECD38C2AE47) dictionary view, that became available in Oracle Database 12.2.
